import Moment from "react-moment";

const heatColumns = [
    // {
    //   name: "ID",
    //   cell: (row) => row.id,
    //   sortable: true,
    //   center: false,
    //   wrap: true,
    //   grow: 0,
    // },
    {
      name: "REVISION",
      cell: (row) => <Moment date={row.revision} format="DD/MM/YYYY HH:mm:ss" />,
      sortable: true,
      center: false,
      wrap: true,
      grow: 1,
    },
    {
      name: "HEAT_CODE",
      cell: (row) => row.heatCode,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "HEAT_SEQ",
      cell: (row) => row.heatSeq,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
   
    {
      name: "STEEL_GRADE_CODE",
      cell: (row) => row.steelGradeCode,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "ALLOCATED_SP",
      cell: (row) => row.allocatedSP,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "CHARGED_SP",
      cell: (row) => row.chargedSP,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "ROUGHED_SP",
      cell: (row) => row.roughedSP,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "STATUS",
      cell: (row) => row.status,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "PROFILE_CODE",
      cell: (row) => row.profileCode,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "WEIGHT",
      cell: (row) => row.weight,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "LENGTH",
      cell: (row) => row.length,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "TRG_CLOSED",
      cell: (row) => row.trgClosed,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "BILLET_ADDED",
      cell: (row) => row.billetAdded,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "START_CHARGED",
      cell: (row) => row.startCharged,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "END_CHARGED",
      cell: (row) => row.endCharged,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "START_ROUGHED",
      cell: (row) => row.startRoughed,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "END_ROUGHED",
      cell: (row) => row.endRoughed,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "PRODUCED_COUNT",
      cell: (row) => row.producedCount,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
    {
      name: "REJECT_COUNT",
      cell: (row) => row.rejectCount,
      sortable: true,
      center: true,
      wrap: true,
      grow: 1,
    },
  ];
  
  export default heatColumns;
  