import Moment from "react-moment";

const standsColumns = [
  // {
  //   name: "ID",
  //   cell: (row) => row.Id,
  //   sortable: true,
  //   center: false,
  //   wrap: true,
  //   grow: 1,
  // },
  {
    name: "Q_Date",
    cell: (row) => <Moment date={row.Q_DATE} format="DD/MM/YYYY" />,
    sortable: true,
    center: false,
    wrap: true,
    grow: 1,
    width: "105px",
  },
  {
    name: "St#1",
    cell: (row) => row.DAILY_CONS_01,
    sortable: true,
    center: true,
    wrap: true,
    grow: 1,
  },
  {
    name: "St#3",
    cell: (row) => row.DAILY_CONS_03,
    sortable: true,
    center: true,
    wrap: true,
    grow: 1,
  },
  {
    name: "St#5",
    cell: (row) => row.DAILY_CONS_05,
    sortable: true,
    center: true,
    wrap: true,
    grow: 1,
  },
  {
    name: "St#7",
    cell: (row) => row.DAILY_CONS_07,
    sortable: true,
    center: true,
    wrap: true,
    grow: 1,
  },
  {
    name: "St#9",
    cell: (row) => row.DAILY_CONS_09,
    sortable: true,
    center: true,
    wrap: true,
    grow: 1,
  },
  {
    name: "St#11",
    cell: (row) => row.DAILY_CONS_11,
    sortable: true,
    center: true,
    wrap: true,
    grow: 1,
  },
  {
    name: "St#13",
    cell: (row) => row.DAILY_CONS_13,
    sortable: true,
    center: true,
    wrap: true,
    grow: 1,
  },
  {
    name: "St#14",
    cell: (row) => row.DAILY_CONS_14,
    sortable: true,
    center: true,
    wrap: true,
    grow: 1,
  },
  {
    name: "PGV1_M1",
    cell: (row) => row.PGV1_M1,
    sortable: true,
    center: true,
    wrap: false,
    grow: 1,
  },
  {
    name: "PGV1_M2",
    cell: (row) => row.PGV1_M2,
    sortable: true,
    center: true,
    wrap: false,
    grow: 1,
  },
  {
    name: "PGV2_M1",
    cell: (row) => row.PGV2_M1,
    sortable: true,
    center: true,
    wrap: true,
    grow: 1,
  },
  {
    name: "PGV2_M2",
    cell: (row) => row.PGV2_M2,
    sortable: true,
    center: true,
    wrap: true,
    grow: 1,
  },
  {
    name: "DAILY_RHF",
    cell: (row) => row.DAILY_RHF,
    sortable: true,
    center: true,
    wrap: true,
    grow: 1,
  },
];

export default standsColumns;
