import { LoadingButton } from "@mui/lab";
// import { Stack } from "@mui/material";
import BorderColorIcon from "@mui/icons-material/BorderColor";
import AddCircleOutlineIcon from "@mui/icons-material/AddCircleOutline";
import { deepOrange, deepPurple } from "@mui/material/colors";
import GridViewIcon from "@mui/icons-material/GridView";
import CloudUploadIcon from "@mui/icons-material/CloudUpload";
import SearchIcon from "@mui/icons-material/Search";
import SearchOffIcon from '@mui/icons-material/SearchOff';
import BoltIcon from '@mui/icons-material/Bolt';
import AvTimerIcon from '@mui/icons-material/AvTimer';
import AssessmentIcon from '@mui/icons-material/Assessment';
import {
  Stack,
  Button,
  TextField,
  Box,
  InputAdornment,
  IconButton,
  AppBar,
  Toolbar,
  Typography,
  Container,
  Menu,
  Select,
  MenuItem,
  Drawer,
  List,
  Divider,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Avatar,
  Tooltip,
  Card,
  CardContent,
  Checkbox,
  Grid,
  CircularProgress,
  LinearProgress
} from "@mui/material";

import {
  Visibility as VisibilityIcon,
  VisibilityOff as VisibilityOffIcon,
  AccountCircle,
  MailOutline as MailOutlineIcon,
  Key as KeyIcon,
  Menu as MenuIcon,
  Adb as AdbIcon,
  LockOpen as LockOpenIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  Inbox as InboxIcon,
  Person as PersonIcon,
  ProductionQuantityLimits as ProductionQuantityLimitsIcon,
  DeleteForever as DeleteForeverIcon,
  SettingsBackupRestore as SettingsBackupRestoreIcon,
  ControlPoint as ControlPointIcon,
  Dashboard as DashboardIcon,
  AppRegistration as AppRegistrationIcon,
  Logout as LogoutIcon,
  Login as LoginIcon,
  PrecisionManufacturing as PrecisionManufacturingIcon,
  ErrorOutline as ErrorOutlineIcon,
  CheckCircleOutline as CheckCircleOutlineIcon,
  Factory as FactoryIcon,
} from "@mui/icons-material";
import ElectricRickshawIcon from '@mui/icons-material/ElectricRickshaw';
import AutoDeleteIcon from '@mui/icons-material/AutoDelete';
export const Data = {
  AutoDeleteIcon,
  ElectricRickshawIcon,
  SearchIcon,
  SearchOffIcon,
  GridViewIcon,
  deepOrange,
  deepPurple,
  CloudUploadIcon,
  Stack,
  FactoryIcon,
  AddCircleOutlineIcon,
  LoadingButton,
  Button,
  TextField,
  Box,
  InputAdornment,
  IconButton,
  AppBar,
  Toolbar,
  Typography,
  Container,
  Menu,
  Select,
  MenuItem,
  Drawer,
  List,
  Divider,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Avatar,
  Tooltip,
  Card,
  CardContent,
  Checkbox,
  Grid,
  LinearProgress,
  CircularProgress,
  VisibilityIcon,
  VisibilityOffIcon,
  AccountCircle,
  MailOutlineIcon,
  KeyIcon,
  MenuIcon,
  AdbIcon,
  LockOpenIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  InboxIcon,
  PersonIcon,
  ProductionQuantityLimitsIcon,
  DeleteForeverIcon,
  SettingsBackupRestoreIcon,
  ControlPointIcon,
  DashboardIcon,
  AppRegistrationIcon,
  LogoutIcon,
  LoginIcon,
  PrecisionManufacturingIcon,
  ErrorOutlineIcon,
  CheckCircleOutlineIcon,
  BorderColorIcon,
  BoltIcon,
  AvTimerIcon,
  AssessmentIcon
};
